export interface Tool {
  id: string;
  name: string;
  path: string;
  description: string;
  icon: string;
  keywords: string[];
  group: string;
}

export const groups = [
  { label: "Network", ids: ["my-ip", "privacy-check", "webrtc-leak-test", "dns-lookup", "email-auth", "port-scan", "is-it-down", "is-it-up"] },
  { label: "Security", ids: ["ssl-checker", "http-headers", "whois-lookup", "redirect-checker"] },
  { label: "Calculators", ids: ["subnet-calculator", "ip-converter", "password-strength", "jwt-decoder", "url-parser"] },
];

export const tools: Tool[] = [
  {
    id: "my-ip",
    name: "What Is My IP",
    path: "/my-ip",
    description: "See your public IP address, location, ISP, and network details",
    icon: "Ip",
    keywords: ["what is my ip", "my ip address", "check ip", "public ip"],
    group: "Network",
  },
  {
    id: "privacy-check",
    name: "Browser Privacy Check",
    path: "/privacy-check",
    description: "Check your browser's privacy settings, tracking protection, and fingerprint exposure",
    icon: "Pv",
    keywords: ["browser privacy check", "privacy test", "tracking protection", "fingerprint test"],
    group: "Network",
  },
  {
    id: "webrtc-leak-test",
    name: "WebRTC Leak Test",
    path: "/webrtc-leak-test",
    description: "Check if WebRTC is leaking your real IP address",
    icon: "Wl",
    keywords: ["webrtc leak test", "webrtc ip leak", "vpn leak test"],
    group: "Network",
  },
  {
    id: "subnet-calculator",
    name: "Subnet Calculator",
    path: "/subnet-calculator",
    description: "Calculate network address, broadcast, host range from CIDR notation",
    icon: "Sn",
    keywords: ["subnet calculator", "cidr calculator", "ip subnet", "network calculator"],
    group: "Calculators",
  },
  {
    id: "ip-converter",
    name: "IP Address Converter",
    path: "/ip-converter",
    description: "Convert IP addresses between decimal, binary, hexadecimal, and octal",
    icon: "Ic",
    keywords: ["ip converter", "ip to binary", "ip to hex", "decimal to ip"],
    group: "Calculators",
  },
  {
    id: "password-strength",
    name: "Password Strength Checker",
    path: "/password-strength",
    description: "Analyze password entropy, crack time estimation, and strength rating",
    icon: "Pw",
    keywords: ["password strength", "password checker", "how strong is my password", "password entropy"],
    group: "Calculators",
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    path: "/jwt-decoder",
    description: "Decode and inspect JSON Web Tokens \u2014 header, payload, and signature",
    icon: "Jw",
    keywords: ["jwt decoder", "jwt debugger", "decode jwt", "json web token"],
    group: "Calculators",
  },
  {
    id: "dns-lookup",
    name: "DNS Lookup",
    path: "/dns-lookup",
    description: "Query DNS records for any domain \u2014 A, AAAA, MX, CNAME, TXT, NS, SOA",
    icon: "Dn",
    keywords: ["dns lookup", "dns checker", "dns query", "nslookup online"],
    group: "Network",
  },
  {
    id: "email-auth",
    name: "Email Auth",
    path: "/email-auth",
    description: "Check SPF, DKIM, and DMARC records for any domain",
    icon: "Em",
    keywords: ["spf checker", "dkim checker", "dmarc checker", "email authentication", "spf record", "dkim record", "dmarc record", "email security"],
    group: "Network",
  },
  {
    id: "port-scan",
    name: "Port Scanner",
    path: "/port-scan",
    description: "Scan common ports on any host to check which services are reachable",
    icon: "Ps",
    keywords: ["port scanner", "port check", "open ports", "port scan online", "port checker"],
    group: "Network",
  },
  {
    id: "ssl-checker",
    name: "SSL Checker",
    path: "/ssl-checker",
    description: "Check SSL/TLS certificate status, HSTS, and certificate transparency logs",
    icon: "Sl",
    keywords: ["ssl checker", "ssl test", "ssl certificate checker", "https checker"],
    group: "Security",
  },
  {
    id: "is-it-down",
    name: "Is It Down?",
    path: "/is-it-down",
    description: "Check if a website is down for everyone or just you",
    icon: "Dw",
    keywords: ["is it down", "website down checker", "is this site down", "site status"],
    group: "Network",
  },
  {
    id: "is-it-up",
    name: "Website Status",
    path: "/is-it-up",
    description: "Check website uptime, response time, and server status",
    icon: "Up",
    keywords: ["is it up", "website status", "uptime checker", "response time"],
    group: "Network",
  },
  {
    id: "http-headers",
    name: "HTTP Headers",
    path: "/http-headers",
    description: "Inspect HTTP response headers and security header analysis",
    icon: "Hd",
    keywords: ["http headers", "response headers", "security headers", "header checker"],
    group: "Security",
  },
  {
    id: "whois-lookup",
    name: "WHOIS Lookup",
    path: "/whois-lookup",
    description: "Look up domain registration details, registrar, and nameservers via RDAP",
    icon: "Wh",
    keywords: ["whois lookup", "domain whois", "domain lookup", "who owns domain"],
    group: "Security",
  },
  {
    id: "redirect-checker",
    name: "Redirect Checker",
    path: "/redirect-checker",
    description: "Trace the full redirect chain of any URL with status codes",
    icon: "Rd",
    keywords: ["redirect checker", "redirect trace", "url redirect", "301 redirect checker"],
    group: "Security",
  },
  {
    id: "url-parser",
    name: "URL Parser",
    path: "/url-parser",
    description: "Parse and break down URLs into protocol, host, path, query params, and hash",
    icon: "Ur",
    keywords: ["url parser", "url decoder", "parse url", "url breakdown"],
    group: "Calculators",
  },
];
