/**
 * Post-build: append Cloudflare Early Hints (HTTP 103) Link headers to
 * dist/_headers. CF Pages auto-promotes Link: <X>; rel=preload to a 103
 * Early Hints response sent during origin think-time, so the browser
 * begins fetching CSS before the HTML body arrives.
 *
 * Reference: https://developers.cloudflare.com/pages/configuration/early-hints/
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const distDir = './dist';
const headersPath = join(distDir, '_headers');
const astroDir = join(distDir, '_astro');

const cssFiles = readdirSync(astroDir).filter(f => f.endsWith('.css'));

// PingThat: every page imports the same single tools.HASH.css bundle.
function pickUnique(re, label) {
  const matches = cssFiles.filter(f => re.test(f));
  if (matches.length > 1) {
    throw new Error(`[early-hints] Multiple ${label} matches in dist/_astro/: ${matches.join(', ')}. Clean dist/ and rebuild.`);
  }
  return matches[0] ?? null;
}
const toolsCss = pickUnique(/^tools\..*\.css$/, 'tools.*.css');

if (!toolsCss) {
  console.log('[early-hints] no tools.*.css found in _astro/, skipping');
  process.exit(0);
}

const link = `Link: </_astro/${toolsCss}>; rel=preload; as=style`;

const earlyHintsBlock = [
  '# Cloudflare Early Hints (HTTP 103) — auto-generated by',
  '# scripts/early-hints.mjs after each build. Preloads the CSS bundle',
  '# during origin think-time, so cold-visit FCP/LCP improve without',
  '# inflating HTML payload. CF only emits 103 on HTML responses.',
  '/*',
  `  ${link}`,
  '',
  '',
].join('\n');

const existing = readFileSync(headersPath, 'utf-8');
writeFileSync(headersPath, earlyHintsBlock + existing);
console.log(`[early-hints] prepended Link header to dist/_headers`);
console.log(`[early-hints]   tools: ${toolsCss}`);
